'''
Written by: Matt Scanlon
Written on: 2022-07-31 9:30 PM
Last Updated by: Matt Scanlon
Last Updated on: 2022-08-17 9:00 AM

Generated by insomnia in a few steps:
 - navigate to page
 - right click element - inspect
 - select network -> Fetch/XHR
 - refresh page
 - select last 7 days
 - Find GET request (right click table and select method if needed)
 - Right click -> copy -> copy cURL
 - paste and send in insomnia
 - right click request on the left 

PURPOSE:
-To gather this week's list of best batters
REQUIREMENTS:
-requests, pandas
'''
# Imports----------------------------------------------------------------------
import requests
import pandas
import os
# Local Dependencies-----------------------------------------------------------
from skunkpack import datestrings
from skunkpack import logger
data_path = os.getcwd()+'\\__data\\Baseball_Data\\'
'''pymysql connection
pymysql_connection = pymysql.connect(
    'skunkworks.cnr2lzj6zcdf.us-east-1.rds.amazonaws.com'
    'admin','password')
'''
# Definitions------------------------------------------------------------------
url = "https://bdfed.stitch.mlbinfra.com/bdfed/stats/player"
querystring = {"stitch_env":"prod","season":"2022","sportId":"1", \
                "stats":"season","group":"hitting","gameType":"R", \
                "limit":"25","offset":"0","sortStat":"onBasePlusSlugging", \
                "order":"desc","daysBack":"-365"
            }
payload = ""
# Main-------------------------------------------------------------------------
logger.log.debug(f'top_25_hitters request was made to mlbinfra.com')
response = requests.request("GET", url, data=payload, params=querystring)
data = response.json()
stats = data['stats']
df = pandas.json_normalize(stats)
time_executed = f'{datestrings.todays_date}_{datestrings.right_now_24}'
file_name = f'top25_hitters_week_to_date_{time_executed}.csv'
try:
    df.to_csv(data_path+file_name, index=False)
    logger.log.debug(f'{file_name} saved to data folder')
except:
    logger.log.error(f'AN ERROR OCCURED WHEN LOGGING TOP 25 HITTERS')
'''
#attempt at messing with pymysql via pandas
try:
    df.to_sql()
    logger.log.debug(f'{file_name} saved to data folder')
except:
    logger.log.error('AN ERROR OCCURED WHEN LOGGING TOP 25 HITTERS TODAY')
'''