'''
Generated by insomnia in a few steps:
 - navigate to page
 - right click element - inspect
 - select network -> Fetch/XHR
 - refresh page
 - select last 7 days
 - Find GET request (right click table and select method if needed)
 - Right click -> copy -> copy cURL
 - paste and send in insomnia
 - right click request on the left 

PURPOSE:
-To test uses for insomnia queries
-To gather this week's list of best batters
REQUIREMENTS:
-requests, pandas
'''
#Imports----------------------------------------------------------------------
import requests
import pandas as pd
#Local Dependencies-----------------------------------------------------------
from formatdates import date_strings
from set_logs import logger
data_path = 'C:\\Users\\mscanlon\\source\\repos\\skunkworks\\0. Data\\'
#Definitions------------------------------------------------------------------
url = "https://bdfed.stitch.mlbinfra.com/bdfed/stats/player"
querystring = {"stitch_env":"prod","season":"2022","sportId":"1", \
    "stats":"season","group":"hitting","gameType":"R","limit":"25", \
        "offset":"0","sortStat":"onBasePlusSlugging","order":"desc","daysBack":"-6"
            }
payload = ""
#Main-------------------------------------------------------------------------
response = requests.request("GET", url, data=payload, params=querystring)
data = response.json()
stats = data['stats']
df = pd.json_normalize(stats)
try:
    df.to_csv(data_path + f'top25_hitters_this_week_to_date_eod_{date_strings.todays_date}.csv', index=False)
    logger.log.debug('Top 25 hitters logged to_csv in data folder')
except:
    logger.log.error('AN ERROR OCCURED WHEN LOGGING TOP 25 HITTERS TODAY')